### ISSUE TITLE
`UNSUPPORTED_OPERATION` Error when using `Token.create` in Moonshot EVM SDK

### ISSUE THREAD

**Issue by xpelch** [wen-moon-ser/moonshot-sdk-evm#2]
### Issue:
I'm encountering an `UNSUPPORTED_OPERATION` error when trying to create a token using the `Moonshot EVM SDK`. The error appears during the `Token.create` call, and it seems related to an unsupported `contract runner` operation. I've followed the code snippets provided in the GitHub repo documentation, and verified my provider and signer setup, but the error persists.

**Error Details**:
Here’s the full error trace:
```
An error occurred: Error: contract runner does not support calling (operation="call", code=UNSUPPORTED_OPERATION, version=6.13.4)
    at makeError (C:\Crypto\moonshot-bot\node_modules\@wen-moon-ser\moonshot-sdk-evm\node_modules\ethers\lib.commonjs\utils\errors.js:129:21)
    at assert (C:\Crypto\moonshot-bot\node_modules\@wen-moon-ser\moonshot-sdk-evm\node_modules\ethers\lib.commonjs\utils\errors.js:149:15)
    at staticCallResult (C:\Crypto\moonshot-bot\node_modules\@wen-moon-ser\moonshot-sdk-evm\node_modules\ethers\lib.commonjs\contract\contract.js:241:31)
    at staticCall (C:\Crypto\moonshot-bot\node_modules\@wen-moon-ser\moonshot-sdk-evm\node_modules\ethers\lib.commonjs\contract\contract.js:219:30)
    at Proxy.curveType (C:\Crypto\moonshot-bot\node_modules\@wen-moon-ser\moonshot-sdk-evm\node_modules\ethers\lib.commonjs\contract\contract.js:259:26)
    at Token.create (C:\Crypto\moonshot-bot\node_modules\@wen-moon-ser\moonshot-sdk-evm\dist\domain\token\Token.js:18:51)
    at buyToken (file:///C:/Crypto/moonshot-bot/src/transactions/buy.js:20:29)
    at main (file:///C:/Crypto/moonshot-bot/src/app.js:18:27)
    at file:///C:/Crypto/moonshot-bot/src/app.js:34:1
    at ModuleJob.run (node:internal/modules/esm/module_job:195:25) {
  code: 'UNSUPPORTED_OPERATION',
  operation: 'call',
  shortMessage: 'contract runner does not support calling'
}
```

**Code to Reproduce**:
Here’s the code I’m using based on the example in the documentation:

```javascript
import dotenv from 'dotenv';
dotenv.config();

import { ethers } from 'ethers';
import { Moonshot, Token, FixedSide, Environment } from '@wen-moon-ser/moonshot-sdk-evm';

const buyToken = async (tokenAmount) => {
  const rpcUrl = process.env.RPC_URL;
  const privateKey = process.env.PRIVATE_KEY;
  const testTokenAddress = '0x3a0b85a42cbac2e37f0efaa371c2d2250ea1b2c0'

  const provider = new ethers.JsonRpcProvider(rpcUrl);
  const signer = new ethers.Wallet(privateKey, provider);

  const moonshot = new Moonshot({
    signer: signer,
    env: Environment.MAINNET,
  });

  const token = await Token.create({
    tokenAddress: testTokenAddress,
    moonshot,
  });

  const collateralAmount = await token.getCollateralAmountByTokens({
    tokenAmount,
    tradeDirection: 'BUY',
  });

  const tx = await token.prepareTx({
    slippageBps: 500,
    tokenAmount,
    collateralAmount,
    tradeDirection: 'BUY',
    fixedSide: FixedSide.OUT,
  });

  tx.from = await signer.getAddress();
  tx.gasLimit = await provider.estimateGas(tx);

  const { maxFeePerGas, maxPriorityFeePerGas } = await provider.getFeeData();
  tx.maxFeePerGas = maxFeePerGas;
  tx.maxPriorityFeePerGas = maxPriorityFeePerGas;

  const txResponse = await signer.sendTransaction(tx);
  console.log('Buy transaction hash:', txResponse.hash);
};
```

**Environment**:
- SDK Version: Moonshot EVM SDK (latest version from repo)
- ethers.js Version: 6.13.4
- Node.js Version: 18.20.4
- Network: Base

**Troubleshooting Steps Taken**:
- Verified `provider` and `signer` are correctly configured.
- Tried different RPC endpoints.
- Increased `gasLimit`, `maxFeePerGas`, and `maxPriorityFeePerGas` in the transaction (no effect on the error).

**Expected Behavior**:
The `Token.create` function should initialize a new token object without causing an unsupported operation error.

**Actual Behavior**:
The `Token.create` call triggers an `UNSUPPORTED_OPERATION` error, specifically related to the `contract runner` not supporting a `call` operation.

**Additional Context**:
It seems like the error may be due to an incorrect configuration of the contract runner within the SDK, where a signer is being used for a read-only call (`eth_call`). Any guidance on configuring the SDK or modifying the runner to prevent this error would be greatly appreciated.

**Comment by alanwatts07** [comment]
> ###
> **[xpelch](/xpelch) ** commented [Nov 2, 2024](#issue-2630732915) •

Yup I will second that... working on it, but I am not getting to far.

**Comment by alanwatts07** [comment]
I even tried initializing the moonshot class with a provider instead of a signer and flipped those around several times trying to see if I could figure out exactly where it was happening.

Same error each time

**Comment by mavagio** [comment]
@alanwatts07 @xpelch thanks for reporting @vpatsenko is working on this and will get back to you

**Comment by vpatsenko** [comment]
Hey @alanwatts07! We fixed the issue. Could you update to the latest version?

**Comment by alanwatts07** [comment]
thankswill try it now=]

**Comment by alanwatts07** [comment]
> Hey @alanwatts07! We fixed the issue. Could you update to the latest version?

I was able to make it work in TS
