### ISSUE TITLE
Versioning issue

### ISSUE THREAD

**Issue by alanwatts07** [wen-moon-ser/moonshot-sdk-evm#7]
The default version I get with npm install @wen-....  is returning an error and a depreciated message which is an easy manual fix but I figured you would want to know. I went to install in a different venv and it started failing.

**Comment by alanwatts07** [comment]
something about version 4.1.0 being wrong and changing to 4.0.1

**Comment by vpatsenko** [comment]
@alanwatts07 I think you're having an issue with the solana sdk. Could you create an issue there?

**Comment by alanwatts07** [comment]
yes oops
